name = "my-astro-site"
compatibility_date = "2024-11-20"
main = "src/workers/index.js"

[[d1_databases]]
binding = "user_db"
database_name = "user-db"
database_id = "e15a74e9-ed9c-4e4c-b2c7-9a19be61eb06"
migrations_dir = "migrations"
